# Application configuration
spring.application.name=task-scheduler

spring.data.mongodb.uri=mongodb://localhost:27017/db_agendador

server.port=9090

# Chave secreta para valida��o do JWT. Deve ser a mesma do servi�o de autentica��o.
jwt.secret=a2a6d8a8fabe3a5f3a3a7f9b3a5b3a5b3a5b3a5b3a5b3a5b3a5b3a5b3a5b3a5b
